name: chesschallenge
author: Anders Forsell <aforsell1971@gmail.com>
description: A multi-player game where you compete in solving chess problems as fast as possible.
dependencies:
  chessboard: '>=0.1.1 <0.1.2'
  core_elements: '>=0.4.0 <0.5.0'
  firebase: '>=0.2.0 <0.3.0'
  http: '>=0.11.1 <0.12.0'
  paper_elements: '>=0.5.0 <0.6.0'
  path: '>=1.3.0 <1.4.0'
  polymer: '>=0.15.1 <0.15.2'
  shelf: '>=0.5.5 <=0.6.0'
  shelf_web_socket: '>=0.0.1 <0.1.0'
transformers:
- polymer:
    entry_points: web/index.html
